# Generated by Django 2.1.5 on 2019-02-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
    ]
