# Generated by Django 2.1.7 on 2019-02-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_select',
            field=models.DateTimeField(verbose_name='日付-時間'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_for',
            field=models.PositiveIntegerField(verbose_name='利用時間[時間]'),
        ),
    ]
