# Generated by Django 2.1.5 on 2019-02-15 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=30, verbose_name='エリア')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=30, verbose_name='施設名')),
                ('address', models.CharField(max_length=300, verbose_name='住所')),
                ('picture', models.CharField(max_length=300, verbose_name='画像')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=-1)),
                ('last_name', models.CharField(max_length=10, verbose_name='姓')),
                ('first_name', models.CharField(max_length=10, verbose_name='名')),
                ('group', models.CharField(max_length=30, verbose_name='団体名')),
                ('man_in', models.PositiveIntegerField(verbose_name='市内男性人数')),
                ('man_out', models.PositiveIntegerField(verbose_name='市内女性人数')),
                ('woman_in', models.PositiveIntegerField(verbose_name='市外男性人数')),
                ('woman_out', models.PositiveIntegerField(verbose_name='市外女性人数')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='メールアドレス')),
                ('phone', models.PositiveIntegerField(verbose_name='電話番号')),
                ('date_select', models.DateTimeField(verbose_name='日付')),
                ('time_for', models.PositiveIntegerField(verbose_name='利用時間')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='UseKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(max_length=50, verbose_name='利用目的')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='use_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.UseKind'),
        ),
    ]
