# Generated by Django 2.1.5 on 2019-02-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190215_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=30, verbose_name='部屋名')),
            ],
        ),
        migrations.RemoveField(
            model_name='facility',
            name='Area',
        ),
        migrations.AddField(
            model_name='facility',
            name='Area',
            field=models.ManyToManyField(to='system.Area'),
        ),
        migrations.AddField(
            model_name='facility',
            name='room',
            field=models.ManyToManyField(to='system.Room'),
        ),
    ]
